# Generated by Django 4.1.5 on 2023-02-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_orderitem_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tarif_livraison',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
